# -----------
# General Configs
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

# -------------
# Theme Configs
# https://github.com/pages-themes/hacker#customizing
title: pyzlnar's github.io
description: much hacker, so cool!
